"use strict";

/**
 * Factory for the agents whose whole job is "read what the buyer typed, write
 * a structured document back".
 *
 * They differ only in the brief, so the shared parts live here: the input is
 * always fenced as untrusted before a model sees it, the output is always
 * markdown with a real heading (the judge requires one), and a model that
 * returns nothing usable fails loudly rather than delivering an empty file that
 * would be rejected and refunded.
 */

const { generate } = require("../llm");
const { fence, UNTRUSTED_NOTICE } = require("../untrusted");

/**
 * @param {object} spec
 * @param {string} spec.key      catalog key
 * @param {string} spec.title    display name
 * @param {string} spec.field    the single input field this agent reads
 * @param {number} [spec.minChars]  reject obviously empty input
 * @param {number} [spec.maxTokens]
 * @param {(value: string) => string} spec.brief  the instructions, minus the input
 */
function writer({ key, title, field, brief, minChars = 3, maxTokens = 2048 }) {
  async function run(input) {
    const value = String(input?.[field] ?? "").trim();
    if (value.length < minChars) throw new Error(`give me a ${field} to work from`);

    const prompt = [
      brief(value),
      "",
      "Reply with markdown only. Start with a single `# ` heading. No preamble, no",
      "closing pleasantries, no offer to help further.",
      "",
      UNTRUSTED_NOTICE,
      fence(value),
    ].join("\n");

    const { text, model } = await generate(prompt, { maxOutputTokens: maxTokens });
    const body = String(text || "").trim();
    // Better to fail here and retry than to deliver something the judge will
    // reject — a rejection refunds the buyer and costs the agent its fee.
    if (body.length < 200) throw new Error("the model returned too little to be worth delivering");

    const content = /^#\s/m.test(body) ? body : `# ${title}\n\n${body}`;
    return {
      content: `${content}\n\n---\n*Generated by the ${title} agent on Stubly (model: ${model}).*\n`,
      contentType: "text/markdown",
    };
  }

  return { key, title, run };
}

module.exports = { writer };
