"use strict";

/**
 * Arc-native agent — Agent Lookup. Due diligence on other agents.
 * Input:  { agent }  (an ERC-8004 agent id, or the wallet address that owns one)
 * Output: who this agent is, its published card, who owns it, and whether the
 * claims check out. This is the one an AI buys before hiring another AI.
 */

const { Contract } = require("ethers");
const { provider } = require("../../chain/config");
const { REGISTRY, IDENTITY_ABI } = require("../../chain/registry");
const C = require("./_chain");

async function run(input) {
  const raw = String(input.agent || "").trim();
  if (!raw) throw new Error("give an ERC-8004 agent id (a number) or an owner address");

  const prov = provider();
  const identity = new Contract(REGISTRY.identity, IDENTITY_ABI, prov);

  let agentId = null;
  if (/^\d+$/.test(raw)) agentId = raw;
  else if (C.isAddress(raw)) {
    // find identity NFTs held by this address via the explorer
    const held = await C.get(`/addresses/${raw}/nft?type=ERC-721`);
    const mine = (held?.items || []).filter((n) => (n.token?.address_hash || n.token?.address || "").toLowerCase() === REGISTRY.identity.toLowerCase());
    if (!mine.length) throw new Error(`no ERC-8004 agent identity found for ${C.short(raw)}`);
    agentId = String(mine[0].id);
  } else throw new Error("input must be an agent id or a 0x… address");

  let uri = null, owner = null;
  try { uri = await identity.tokenURI(agentId); } catch { /* may not exist */ }
  try { owner = await identity.ownerOf(agentId); } catch { /* may not exist */ }
  if (!owner) throw new Error(`agent #${agentId} is not registered in the identity registry`);

  let card = null, cardError = null;
  if (uri) {
    try {
      const url = uri.startsWith("ipfs://") ? uri.replace("ipfs://", "https://ipfs.io/ipfs/") : uri;
      const r = await fetch(url, { signal: AbortSignal.timeout(10_000) });
      card = r.ok ? await r.json() : null;
      if (!r.ok) cardError = `card URL returned ${r.status}`;
    } catch (e) { cardError = e.message; }
  }

  const ownerInfo = await C.get(`/addresses/${owner}`);
  const checks = [
    [`Identity NFT #${agentId} exists on-chain`, true],
    ["Card URL published", Boolean(uri)],
    ["Card is reachable and valid JSON", Boolean(card)],
    ["Owner wallet has on-chain history", Boolean(ownerInfo?.transactions_count)],
  ];

  const content = `# Agent Lookup: #${agentId}

Registered in Circle's ERC-8004 IdentityRegistry on Arc.
[View identity NFT](${C.EXPLORER}/token/${REGISTRY.identity}/instance/${agentId})

## Identity
- Agent id: **#${agentId}**
- Owner wallet: [${C.short(owner)}](${C.EXPLORER}/address/${owner})
- Owner activity: ${ownerInfo?.transactions_count ?? "unknown"} transactions
- Card URI: ${uri ? `\`${uri}\`` : "*(none published)*"}

## Published card
${card ? `- Name: **${card.name || "—"}**
- Description: ${card.description || "—"}
- Type: ${card.agent_type || "—"}
- Capabilities: ${(card.capabilities || []).join(", ") || "—"}
- Price: ${card.pricing ? `${card.pricing.amount} ${card.pricing.currency} per ${card.pricing.per}` : "—"}
- Settlement: ${card.settlement ? `${card.settlement.standard} on ${card.settlement.chain}` : "—"}
- Endpoint: ${card.endpoint || "—"}` : `*(card could not be read${cardError ? ` — ${cardError}` : ""})*`}

## Verification
${checks.map(([label, ok]) => `- ${ok ? "✅" : "⚠️"} ${label}`).join("\n")}

${checks.every(([, ok]) => ok)
  ? "**All checks passed.** This agent is registered, its card is live, and its owner wallet is active."
  : "**Some checks failed.** Treat the failed items as unverified claims before sending this agent money."}

---
*Generated by the Agent Lookup agent (ERC-8004 registry + Arc chain data). Registry: \`${REGISTRY.identity}\`*
`;
  return { content, contentType: "text/markdown" };
}

module.exports = { key: "agent-lookup", title: "Agent Lookup", run };
