"use strict";

/**
 * Arc-native agent — Chain Pulse.
 * Input:  { focus? }  (optional: what the buyer cares about)
 * Output: the current state of Arc — throughput, block time, fees, and what a
 * builder should take from it. Cheap to run, useful daily, and the one report
 * an agent might buy on a schedule.
 */

const { generate } = require("../llm");
const C = require("./_chain");

async function run(input) {
  const focus = String(input.focus || "").slice(0, 200);

  const [stats, blocks, txs] = await Promise.all([
    C.get("/stats"),
    C.get("/blocks?type=block"),
    C.get("/main-page/transactions"),
  ]);
  if (!stats) throw new Error("could not read Arc network stats right now");

  const recent = (blocks?.items || []).slice(0, 20);
  let avgBlockSecs = null;
  if (recent.length > 1) {
    const first = new Date(recent[recent.length - 1].timestamp).getTime();
    const last = new Date(recent[0].timestamp).getTime();
    avgBlockSecs = ((last - first) / 1000 / (recent.length - 1)).toFixed(2);
  }
  const avgTxPerBlock = recent.length
    ? (recent.reduce((s, b) => s + (b.transactions_count || 0), 0) / recent.length).toFixed(1)
    : "?";

  const sampleFees = (txs || []).slice(0, 15).map((t) => Number(BigInt(t.fee?.value || 0)) / 1e18).filter((n) => n > 0);
  const avgFee = sampleFees.length ? (sampleFees.reduce((a, b) => a + b, 0) / sampleFees.length) : null;

  const facts = `total_blocks: ${stats.total_blocks}
total_transactions: ${stats.total_transactions}
transactions_today: ${stats.transactions_today}
average_block_time_ms: ${stats.average_block_time}
measured_block_time_secs: ${avgBlockSecs}
avg_transactions_per_block: ${avgTxPerBlock}
total_addresses: ${stats.total_addresses}
avg_fee_usdc_sampled: ${avgFee != null ? avgFee.toFixed(8) : "unknown"}
gas_used_today: ${stats.gas_used_today}
network_utilization_percent: ${stats.network_utilization_percentage}`;

  let read = "(read unavailable)", model = "-";
  try {
    const o = await generate(
      `You are a chain analyst writing a short daily pulse on Arc, Circle's stablecoin L1 where USDC is the native gas token. From ONLY these measurements, write <=150 words of markdown bullets: how busy the chain is, what fees and block times mean in practice for someone building payments or agent apps, and one thing worth watching.${focus ? ` The buyer specifically cares about: ${focus}.` : ""} Never invent numbers.\n\n${facts}`,
      { maxOutputTokens: 600 }
    );
    read = o.text; model = o.model;
  } catch { /* measurements still ship */ }

  const content = `# Arc Chain Pulse

*Measured live from ${C.CHAIN_LABEL}.*

## Throughput
- Total blocks: **${Number(stats.total_blocks).toLocaleString("en-US")}**
- Total transactions: **${Number(stats.total_transactions).toLocaleString("en-US")}**
- Transactions today: **${Number(stats.transactions_today || 0).toLocaleString("en-US")}**
- Measured block time: **${avgBlockSecs ?? "?"} s** (explorer average: ${(Number(stats.average_block_time || 0) / 1000).toFixed(2)} s)
- Average transactions per block: ${avgTxPerBlock}

## Cost
- Sampled average fee: **${avgFee != null ? avgFee.toFixed(8) : "?"} USDC** per transaction
- Gas used today: ${Number(stats.gas_used_today || 0).toLocaleString("en-US")}
- Network utilisation: ${stats.network_utilization_percentage ?? "?"}%

## Participation
- Total addresses: **${Number(stats.total_addresses || 0).toLocaleString("en-US")}**

## Analyst read
${read}

---
*Generated by the Chain Pulse agent (Arc network data + model: ${model}).*
`;
  return { content, contentType: "text/markdown" };
}

module.exports = { key: "chain-pulse", title: "Chain Pulse", run };
