"use strict";

/**
 * House agent #3 — Contract Check.
 * Input:  { address: string }  (a contract or token address on the configured chain)
 * Output: markdown safety report — verification status, proxy shape, owner powers,
 * age/activity from Blockscout (free), plus a short LLM read of the risks.
 */

const { generate } = require("../llm");
const EXPLORER_API = process.env.EXPLORER_API || "https://testnet.arcscan.app/api/v2";
const { CHAIN_LABEL } = require("./_chain");

const mark = (ok) => (ok ? "✅" : "⚠️");

async function grab(path) {
  const r = await fetch(`${EXPLORER_API}${path}`, { signal: AbortSignal.timeout(10_000) });
  if (!r.ok) return null;
  return r.json();
}

async function run(input) {
  const address = String(input.address || "").trim();
  if (!/^0x[a-fA-F0-9]{40}$/.test(address)) throw new Error("input must be a 0x… address (40 hex chars)");

  const [info, contract] = await Promise.all([
    grab(`/addresses/${address}`),
    grab(`/smart-contracts/${address}`),
  ]);
  if (!info) throw new Error(`address not found on the ${CHAIN_LABEL} explorer`);

  const isContract = info.is_contract === true;
  const verified = contract?.is_verified === true || Boolean(contract?.abi);
  const isProxy = Boolean(contract?.implementations?.length) || /proxy/i.test(contract?.name || "");
  const name = contract?.name || info.name || "(unnamed)";
  // This Blockscout's /counters returns zeros; sample the tx feed for a real number.
  const feed = await grab(`/addresses/${address}/transactions`);
  const txCount = feed?.items?.length ? `${feed.items.length}${feed.items.length >= 50 ? "+" : ""} (recent)` : "no recent activity";
  const creator = info.creator_address_hash || null;

  const ownerFns = (contract?.abi || [])
    .filter((e) => e.type === "function" && /^(set|withdraw|pause|unpause|upgrade|grant|revoke|mint|burn|blacklist|transferOwnership|renounce)/i.test(e.name || ""))
    .map((e) => e.name);

  const facts = `address: ${address}
is_contract: ${isContract}
verified_source: ${verified}
proxy: ${isProxy}
name: ${name}
tx_count: ${txCount}
creator: ${creator}
privileged_functions: ${ownerFns.slice(0, 20).join(", ") || "none visible"}`;

  let llmRead = "(risk summary unavailable)", model = "-";
  try {
    const out = await generate(
      `You are a smart-contract due-diligence analyst. Based ONLY on these observed facts (do not invent), write <=150 words of markdown bullets: overall trust posture, what the privileged functions imply the owner can do, and what a cautious user should check before sending funds. Facts:\n\n${facts}`,
      { maxOutputTokens: 512 }
    );
    llmRead = out.text; model = out.model;
  } catch { /* mechanical report still ships */ }

  const content = `# Contract Check: ${name}

\`${address}\` on ${CHAIN_LABEL}

## Mechanical findings
- ${mark(isContract)} Is a contract: ${isContract ? "yes" : "NO — this is a regular wallet address"}
- ${mark(verified)} Source code verified on explorer: ${verified ? "yes" : "NO — bytecode only, unreadable"}
- ${mark(!isProxy)} Proxy: ${isProxy ? "YES — logic can be swapped by the admin" : "no — logic is fixed"}
- Transactions seen: ${txCount}
- Creator: ${creator ? `\`${creator}\`` : "unknown"}
- Privileged functions${ownerFns.length ? ` (${ownerFns.length})` : ""}: ${ownerFns.length ? ownerFns.slice(0, 12).map((f) => `\`${f}\``).join(", ") : "none visible in ABI"}

## Risk read
${llmRead}

---
*Generated by the Contract Check agent (Blockscout data + model: ${model}). Testnet tooling — not financial advice.*
`;
  return { content, contentType: "text/markdown" };
}

module.exports = { key: "contract-check", title: "Contract Check", run };
