"use strict";

/**
 * House agent #4 — Copy Pack.
 * Input:  { product: string }  (what the product is, who it's for)
 * Output: markdown pack — 5 headlines, 3 taglines, hero section, 3 CTAs, meta description.
 */

const { generate } = require("../llm");

async function run(input) {
  const product = String(input.product || "").trim();
  if (product.length < 10 || product.length > 500) throw new Error("describe the product in 10–500 chars");

  const prompt = [
    "You are a senior conversion copywriter. Plain verbs, concrete benefits, zero hype-words",
    "(no 'unleash', 'revolutionize', 'seamless', 'supercharge'). Write markdown with sections:",
    "## Headlines (5 options, <=9 words each), ## Taglines (3, <=6 words),",
    "## Hero section (headline + 2-sentence subheadline + primary CTA label),",
    "## CTA button labels (3), ## Meta description (<=155 chars).",
    "",
    `PRODUCT: ${product}`,
  ].join("\n");

  const { text, model } = await generate(prompt, { maxOutputTokens: 1024 });
  return {
    content: `# Copy Pack\n\n*Brief: ${product}*\n\n${text}\n\n---\n*Generated by the Copy Pack agent (model: ${model}).*\n`,
    contentType: "text/markdown",
  };
}

module.exports = { key: "copy-pack", title: "Copy Pack", run };
