"use strict";

/**
 * House agent #6 — Data Extract.
 * Input:  { url: string, want?: string }  (page to extract from, and what to pull)
 * Output: markdown — a clean table of the structured data found on the page,
 * plus a machine-readable JSON block. Built for other agents as much as humans.
 */

const { generate } = require("../llm");
const { fence, UNTRUSTED_NOTICE } = require("../untrusted");

async function run(input) {
  let url = String(input.url || "").trim();
  const want = String(input.want || "the main structured data (tables, lists, prices, stats)").slice(0, 200);
  if (!/^https?:\/\//i.test(url)) url = `https://${url}`;
  let parsed;
  try { parsed = new URL(url); } catch { throw new Error("invalid url"); }
  if (!["http:", "https:"].includes(parsed.protocol)) throw new Error("only http(s) urls");

  const res = await fetch(url, {
    redirect: "follow",
    headers: { "user-agent": "Mozilla/5.0 (compatible; DataExtractAgent/1.0)" },
    signal: AbortSignal.timeout(20_000),
  });
  if (!res.ok) throw new Error(`page returned ${res.status}`);
  const html = (await res.text()).slice(0, 400_000);
  const textOnly = html
    .replace(/<script[\s\S]*?<\/script>/gi, "").replace(/<style[\s\S]*?<\/style>/gi, "")
    .replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").slice(0, 12_000);

  const prompt = [
    "You are a data extraction service. From the page text below, extract ONLY what was asked.",
    "Output markdown with: ## Extracted data (a well-formed markdown table),",
    "## JSON (the same data as a fenced json code block, array of objects, snake_case keys).",
    "If the requested data is not present, say exactly what IS available instead. Never invent values.",
    "",
    `REQUESTED: ${want}`,
    `PAGE (${parsed.hostname}): ${textOnly}`,
  ].join("\n");

  const { text, model } = await generate(prompt, { maxOutputTokens: 2048 });
  return {
    content: `# Data Extract: ${parsed.hostname}\n\n*Requested: ${want}*\n\n${text}\n\n---\n*Generated by the Data Extract agent (model: ${model}).*\n`,
    contentType: "text/markdown",
  };
}

module.exports = { key: "data-extract", title: "Data Extract", run };
