"use strict";

/**
 * Agent — Doc Digest.
 * Input:  { url, question? }
 * Output: a long page reduced to what matters — the argument, the facts worth
 * keeping, and a direct answer if the buyer asked something specific.
 */

const { generate } = require("../llm");

async function run(input) {
  let url = String(input.url || "").trim();
  const question = String(input.question || "").slice(0, 300);
  if (!/^https?:\/\//i.test(url)) url = `https://${url}`;
  let parsed;
  try { parsed = new URL(url); } catch { throw new Error("invalid url"); }

  const res = await fetch(url, {
    redirect: "follow",
    headers: { "user-agent": "Mozilla/5.0 (compatible; StublyDocDigest/1.0)" },
    signal: AbortSignal.timeout(25_000),
  });
  if (!res.ok) throw new Error(`page returned ${res.status}`);
  const html = (await res.text()).slice(0, 600_000);

  const title = (html.match(/<title[^>]*>([^<]*)<\/title>/i) || [])[1]?.trim() || parsed.hostname;
  const text = html
    .replace(/<script[\s\S]*?<\/script>/gi, "").replace(/<style[\s\S]*?<\/style>/gi, "")
    .replace(/<nav[\s\S]*?<\/nav>/gi, "").replace(/<footer[\s\S]*?<\/footer>/gi, "")
    .replace(/<[^>]+>/g, " ").replace(/&nbsp;/g, " ").replace(/\s+/g, " ").trim();
  if (text.length < 200) throw new Error("page had almost no readable text (JavaScript-rendered?)");

  const { text: digest, model } = await generate(
    `Digest this page using ONLY its content. Markdown sections: ## In one line, ## Key points (5-8 bullets, each a fact or claim worth keeping), ## Numbers that matter (any figures, dates, prices — omit the section if there are none), ## What it does not say (gaps a careful reader should notice)${question ? `, ## Direct answer (answer this specifically: "${question}" — say plainly if the page does not answer it)` : ""}. Never add outside knowledge.\n\nTITLE: ${title}\nSOURCE: ${url}\n\nCONTENT:\n${text.slice(0, 16_000)}`,
    { maxOutputTokens: 1536 }
  );

  const content = `# Digest: ${title}\n\n*Source: [${parsed.hostname}](${url}) · ${(text.length / 1000).toFixed(1)}k characters read*\n\n${digest}\n\n---\n*Generated by the Doc Digest agent (model: ${model}).*\n`;
  return { content, contentType: "text/markdown" };
}

module.exports = { key: "doc-digest", title: "Doc Digest", run };
