"use strict";

/**
 * Agent — Name Check.
 * Input:  { name }  (a brand or product name)
 * Output: domain availability across the TLDs that matter, plus a collision
 * read. Uses registry RDAP directly (free, authoritative) — never a reseller's
 * "available!" page, which is how people end up on a squatter's landing site.
 */

const { generate } = require("../llm");

const RDAP = [
  ["com", (n) => `https://rdap.verisign.com/com/v1/domain/${n}.com`],
  ["org", (n) => `https://rdap.publicinterestregistry.org/rdap/domain/${n}.org`],
  ["dev", (n) => `https://www.registry.google/rdap/domain/${n}.dev`],
  ["io", (n) => `https://rdap.identitydigital.services/rdap/domain/${n}.io`],
  ["xyz", (n) => `https://rdap.centralnic.com/xyz/domain/${n}.xyz`],
  ["ai", (n) => `https://rdap.identitydigital.services/rdap/domain/${n}.ai`],
];

async function check(name, tld, urlFor) {
  try {
    const r = await fetch(urlFor(name), { redirect: "follow", signal: AbortSignal.timeout(10_000) });
    if (r.status === 404) return { tld, state: "available" };
    if (r.status === 200) return { tld, state: "taken" };
    return { tld, state: "unknown", note: `registry returned ${r.status}` };
  } catch (e) { return { tld, state: "unknown", note: e.name === "TimeoutError" ? "registry timed out" : e.message }; }
}

async function run(input) {
  const name = String(input.name || "").trim().toLowerCase().replace(/[^a-z0-9-]/g, "");
  if (name.length < 2 || name.length > 40) throw new Error("give a name of 2–40 letters");

  const results = [];
  for (const [tld, urlFor] of RDAP) { results.push(await check(name, tld, urlFor)); }

  const icon = { available: "✅", taken: "❌", unknown: "❔" };
  const rows = results.map((r) => `| .${r.tld} | ${icon[r.state]} ${r.state}${r.note ? ` (${r.note})` : ""} |`).join("\n");
  const free = results.filter((r) => r.state === "available").map((r) => `.${r.tld}`);

  let read = "(collision read unavailable)", model = "-";
  try {
    const o = await generate(
      `A founder is considering the brand name "${name}". From your own knowledge, write <=140 words of markdown bullets: any well-known company, product, or trademark using this exact name or a one-letter variation; what industry they are in; and a blunt verdict on whether the name is safe to build on. If you are not confident a collision exists, say so plainly rather than guessing. End with one line: "Verdict: SAFE / RISKY / TAKEN".`,
      { maxOutputTokens: 512 }
    );
    read = o.text; model = o.model;
  } catch { /* domain table still ships */ }

  const content = `# Name Check: ${name}

## Domain availability
| TLD | Status |
|-----|--------|
${rows}

${free.length ? `**Open right now:** ${free.join(", ")}` : "**No clean TLDs found** among the ones checked."}

*Checked directly against each registry's RDAP service — the authoritative source, not a reseller's search page.*

## Collision read
${read}

> A domain being free does not mean the name is free. Confirm the trademark position
> in your own market before printing anything.

---
*Generated by the Name Check agent (registry RDAP + model: ${model}).*
`;
  return { content, contentType: "text/markdown" };
}

module.exports = { key: "name-check", title: "Name Check", run };
