"use strict";

/**
 * Agent — Pitch Critic.
 * Input:  { pitch }
 * Output: the critique a friend won't give you — who actually pays, the one
 * number the whole thing rests on, why you, and the cheapest real-world test.
 * Deliberately not encouraging; applause is the most expensive advice there is.
 */

const { generate } = require("../llm");

async function run(input) {
  const pitch = String(input.pitch || "").trim();
  if (pitch.length < 20 || pitch.length > 3000) throw new Error("describe the idea in 20–3000 characters");

  const { text, model } = await generate(
    [
      "You are a blunt early-stage investor reviewing a pitch. No applause, no hedging, no 'great idea, but'.",
      "Markdown sections:",
      "## Steelman — the strongest honest case FOR this idea (2-3 sentences, argued properly, not strawmanned).",
      "## Who actually pays — the specific buyer, and why they'd move budget for this.",
      "## The load-bearing number — the single assumption that, if wrong, kills it. State it as a number to go verify.",
      "## Why you — what the founder must already have for this to work, and what happens if they don't.",
      "## Who's already doing it — likely incumbents or substitutes from your knowledge; say plainly if you're unsure rather than inventing names.",
      "## Cheapest real test — one experiment runnable in a week for under $100 that would produce a real signal.",
      "## Verdict — one line: BUILD IT / TEST FIRST / DON'T, plus the single reason.",
      "",
      `PITCH: ${pitch}`,
    ].join("\n"),
    { maxOutputTokens: 1536 }
  );

  return {
    content: `# Pitch Critique\n\n> *Reviewed: ${pitch.slice(0, 160)}${pitch.length > 160 ? "…" : ""}*\n\n${text}\n\n---\n*Generated by the Pitch Critic agent (model: ${model}). Opinion, not diligence — verify the load-bearing number yourself.*\n`,
    contentType: "text/markdown",
  };
}

module.exports = { key: "pitch-critic", title: "Pitch Critic", run };
