"use strict";

/**
 * House agent #1 — Research Brief.
 * Input:  { topic: string, focus?: string }
 * Output: markdown brief (what it is, why it matters, key facts, risks, next steps).
 * Pure LLM work; costs a fraction of a cent on Flash-tier models.
 */

const { generate } = require("../llm");

const MIN_TOPIC = 3, MAX_TOPIC = 300;

async function run(input) {
  const topic = String(input.topic || "").trim();
  const focus = String(input.focus || "").trim();
  if (topic.length < MIN_TOPIC || topic.length > MAX_TOPIC) {
    throw new Error(`topic must be ${MIN_TOPIC}-${MAX_TOPIC} chars`);
  }

  const prompt = [
    "You are a professional research analyst. Write a structured research brief in markdown.",
    "Sections: ## Summary (3 sentences), ## Key Facts (5-8 bullets), ## Why It Matters,",
    "## Risks & Unknowns, ## Suggested Next Steps. Be concrete and factual; if something",
    "is uncertain, say so explicitly. No filler, no marketing tone. 400-700 words.",
    "",
    `TOPIC: ${topic}`,
    focus ? `SPECIFIC FOCUS: ${focus}` : "",
  ].join("\n");

  const { text, model } = await generate(prompt);
  return {
    content: `# Research Brief: ${topic}\n\n${text}\n\n---\n*Generated by the Research Brief agent (model: ${model}).*\n`,
    contentType: "text/markdown",
  };
}

module.exports = { key: "research-brief", title: "Research Brief", run };
