"use strict";

/**
 * House agent #2 — Site Audit.
 * Input:  { url: string }
 * Output: markdown report — mechanical checks measured by code (status, HTTPS,
 * response time, size, title/meta/viewport, h1s, link sample) + a short LLM
 * read of the homepage copy. Mostly free; the LLM part is a few hundred tokens.
 */

const { generate } = require("../llm");
const { fence, UNTRUSTED_NOTICE } = require("../untrusted");

function checkmark(ok) { return ok ? "✅" : "❌"; }

async function run(input) {
  let url = String(input.url || "").trim();
  if (!/^https?:\/\//i.test(url)) url = `https://${url}`;
  let parsed;
  try { parsed = new URL(url); } catch { throw new Error("invalid url"); }
  if (!["http:", "https:"].includes(parsed.protocol)) throw new Error("only http(s) urls");

  const t0 = Date.now();
  const res = await fetch(url, {
    redirect: "follow",
    headers: { "user-agent": "Mozilla/5.0 (compatible; SiteAuditAgent/1.0)" },
    signal: AbortSignal.timeout(20_000),
  });
  const html = (await res.text()).slice(0, 500_000);
  const ms = Date.now() - t0;

  const grab = (re) => (html.match(re) || [])[1]?.trim() || "";
  const title = grab(/<title[^>]*>([^<]*)<\/title>/i);
  const metaDesc = grab(/<meta[^>]+name=["']description["'][^>]+content=["']([^"']*)["']/i) ||
                   grab(/<meta[^>]+content=["']([^"']*)["'][^>]+name=["']description["']/i);
  const viewport = /<meta[^>]+name=["']viewport["']/i.test(html);
  const h1Count = (html.match(/<h1[\s>]/gi) || []).length;
  const links = [...html.matchAll(/<a[^>]+href=["'](https?:\/\/[^"']+)["']/gi)].map((m) => m[1]);
  const uniqueLinks = [...new Set(links)].slice(0, 10);

  // Sample external links for obvious breakage (HEAD, best-effort)
  const linkResults = [];
  for (const l of uniqueLinks.slice(0, 5)) {
    try {
      const r = await fetch(l, { method: "HEAD", redirect: "follow", signal: AbortSignal.timeout(8000) });
      linkResults.push({ url: l, ok: r.ok, status: r.status });
    } catch { linkResults.push({ url: l, ok: false, status: "unreachable" }); }
  }

  const textOnly = html.replace(/<script[\s\S]*?<\/script>/gi, "").replace(/<style[\s\S]*?<\/style>/gi, "").replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").slice(0, 4000);
  let llmRead = "(copy review unavailable)", model = "-";
  try {
    const out = await generate(
      `You are a conversion copy reviewer. In <=180 words of markdown bullets, assess this homepage text: is the value proposition clear in 5 seconds, who it's for, one concrete improvement. Text:\n\n${textOnly}`,
      { maxOutputTokens: 512 }
    );
    llmRead = out.text; model = out.model;
  } catch { /* mechanical report still ships */ }

  const content = `# Site Audit: ${parsed.hostname}

## Vitals
- ${checkmark(res.ok)} HTTP status: ${res.status}
- ${checkmark(parsed.protocol === "https:")} HTTPS
- ${checkmark(ms < 3000)} Response time: ${ms} ms ${ms < 3000 ? "" : "(slow)"}
- ${checkmark(html.length < 300_000)} Page weight (HTML): ${(html.length / 1024).toFixed(0)} KB
- ${checkmark(!!title)} Title: ${title ? `"${title}"` : "MISSING"}
- ${checkmark(!!metaDesc)} Meta description: ${metaDesc ? `"${metaDesc.slice(0, 120)}"` : "MISSING"}
- ${checkmark(viewport)} Mobile viewport tag
- ${checkmark(h1Count === 1)} H1 count: ${h1Count} ${h1Count === 1 ? "" : "(should be exactly 1)"}

## Link sample
${linkResults.length ? linkResults.map((r) => `- ${checkmark(r.ok)} ${r.status} — ${r.url}`).join("\n") : "- no external links found"}

## Copy review
${llmRead}

---
*Generated by the Site Audit agent (mechanical checks + model: ${model}).*
`;
  return { content, contentType: "text/markdown" };
}

module.exports = { key: "site-audit", title: "Site Audit", run };
