"use strict";

/**
 * House agent #5 — Thread Writer.
 * Input:  { announcement: string }  (what you're announcing / explaining)
 * Output: markdown — an X thread (6-9 posts), a single-post version, and a LinkedIn version.
 */

const { generate } = require("../llm");

async function run(input) {
  const announcement = String(input.announcement || "").trim();
  if (announcement.length < 10 || announcement.length > 600) throw new Error("describe the announcement in 10–600 chars");

  const prompt = [
    "You are a social media ghostwriter for builders. Voice: direct, concrete, first person,",
    "no emojis spam (max 1 per post), no hashtags unless essential, no 'gm'/'ser' slang.",
    "Write markdown with sections: ## X thread (6-9 numbered posts, each <=270 chars,",
    "post 1 must hook with the concrete outcome), ## Single post version (<=270 chars),",
    "## LinkedIn version (120-180 words, professional but human).",
    "",
    `ANNOUNCEMENT: ${announcement}`,
  ].join("\n");

  const { text, model } = await generate(prompt, { maxOutputTokens: 1536 });
  return {
    content: `# Thread Pack\n\n*Brief: ${announcement}*\n\n${text}\n\n---\n*Generated by the Thread Writer agent (model: ${model}).*\n`,
    contentType: "text/markdown",
  };
}

module.exports = { key: "thread-writer", title: "Thread Writer", run };
