"use strict";

/**
 * Arc-native agent — Token Report.
 * Input:  { address }  (an ERC-20 on Arc)
 * Output: supply, holder count, concentration (what share the top holders control),
 * recent transfer activity, and a risk read. Concentration is the number that
 * actually matters and almost nobody surfaces it plainly.
 */

const { generate } = require("../llm");
const C = require("./_chain");

async function run(input) {
  const address = String(input.address || "").trim();
  if (!C.isAddress(address)) throw new Error("input must be a 0x… token address");

  const [token, holders, transfers, counters] = await Promise.all([
    C.get(`/tokens/${address}`),
    C.get(`/tokens/${address}/holders`),
    C.get(`/tokens/${address}/transfers`),
    C.get(`/tokens/${address}/counters`),
  ]);
  if (!token || !token.symbol) throw new Error(`no ERC-20 token found at that address on ${C.CHAIN_LABEL}`);

  const dec = Number(token.decimals || 0);
  const supply = Number(BigInt(token.total_supply || 0)) / 10 ** dec;
  const list = (holders?.items || []).slice(0, 10);
  const topShare = list.slice(0, 5).reduce((s, h) => s + Number(BigInt(h.value)) / 10 ** dec, 0);
  const concentration = supply > 0 ? (topShare / supply) * 100 : 0;

  const rows = list.map((h, i) => {
    const bal = Number(BigInt(h.value)) / 10 ** dec;
    const pct = supply > 0 ? ((bal / supply) * 100).toFixed(2) : "?";
    return `| ${i + 1} | [${C.short(h.address?.hash)}](${C.EXPLORER}/address/${h.address?.hash}) | ${bal.toLocaleString("en-US", { maximumFractionDigits: 2 })} | ${pct}% |`;
  });

  const facts = `symbol: ${token.symbol}
name: ${token.name}
total_supply: ${supply}
decimals: ${dec}
holder_count: ${token.holders ?? counters?.token_holders_count ?? "unknown"}
transfer_count: ${counters?.transfers_count ?? "unknown"}
top5_concentration_percent: ${concentration.toFixed(1)}
recent_transfers_sampled: ${(transfers?.items || []).length}`;

  let read = "(risk read unavailable)", model = "-";
  try {
    const o = await generate(
      `You are a token analyst. From ONLY these facts about an ERC-20 on ${C.CHAIN_LABEL}, write <=130 words of markdown bullets: distribution health, what the top-holder concentration implies, and what a buyer should verify next. Do not invent price or market data — none exists here. Be blunt about concentration risk.\n\n${facts}`,
      { maxOutputTokens: 512 }
    );
    read = o.text; model = o.model;
  } catch { /* mechanical report still ships */ }

  const content = `# Token Report: ${token.name || token.symbol} (${token.symbol})

\`${address}\` · [view on Arcscan](${C.EXPLORER}/token/${address})

## Supply
- Total supply: **${supply.toLocaleString("en-US", { maximumFractionDigits: 2 })} ${token.symbol}**
- Decimals: ${dec}
- Holders: **${token.holders ?? counters?.token_holders_count ?? "unknown"}**
- Transfers: ${counters?.transfers_count ?? "unknown"}

## Concentration
**Top 5 holders control ${concentration.toFixed(1)}% of supply.**

| # | Holder | Balance | Share |
|---|--------|---------|-------|
${rows.join("\n") || "| — | no holders found | — | — |"}

## Analyst read
${read}

---
*Generated by the Token Report agent (Arc chain data + model: ${model}). Testnet tooling — not financial advice.*
`;
  return { content, contentType: "text/markdown" };
}

module.exports = { key: "token-report", title: "Token Report", run };
