"use strict";

/**
 * Arc-native agent — Transaction Explainer.
 * Input:  { hash }
 * Output: plain-English account of what a transaction actually did — who paid
 * whom, which contract ran, what moved, what it cost, and whether it worked.
 */

const { generate } = require("../llm");
const C = require("./_chain");

async function run(input) {
  const hash = String(input.hash || "").trim();
  if (!C.isTxHash(hash)) throw new Error("input must be a 0x… transaction hash (64 hex chars)");

  const [tx, transfers, logs] = await Promise.all([
    C.get(`/transactions/${hash}`),
    C.get(`/transactions/${hash}/token-transfers`),
    C.get(`/transactions/${hash}/logs`),
  ]);
  if (!tx) throw new Error("transaction not found on Arc testnet");

  const moves = (transfers?.items || []).map((t) => {
    const d = Number(t.token?.decimals || 0);
    const v = t.total?.value ?? t.value;
    return `- ${C.amt(v, d)} ${t.token?.symbol || "tokens"} — ${C.short(t.from?.hash)} → ${C.short(t.to?.hash)}`;
  });

  const events = (logs?.items || [])
    .map((l) => l.decoded?.method_call?.split("(")[0] || l.topics?.[0]?.slice(0, 10))
    .filter(Boolean);
  const eventCounts = {};
  for (const e of events) eventCounts[e] = (eventCounts[e] || 0) + 1;

  const method = tx.method || tx.decoded_input?.method_call?.split("(")[0] || (tx.to ? "plain transfer" : "contract deploy");

  const facts = `status: ${tx.status}
method_called: ${method}
from: ${tx.from?.hash}
to: ${tx.to?.hash} ${tx.to?.name ? `(${tx.to.name})` : ""}
to_is_contract: ${tx.to?.is_contract}
native_usdc_sent: ${C.nat(tx.value)}
fee_usdc: ${C.nat(tx.fee?.value)}
token_movements: ${moves.length}
events_emitted: ${Object.entries(eventCounts).map(([e, n]) => `${e} x${n}`).join(", ") || "none"}
block: ${tx.block_number} at ${tx.timestamp}
decoded_params: ${JSON.stringify(tx.decoded_input?.parameters || []).slice(0, 600)}`;

  let story = "(explanation unavailable)", model = "-";
  try {
    const o = await generate(
      `You are explaining one blockchain transaction to a smart non-expert. Arc is a chain where USDC IS the gas token. From ONLY these facts, write markdown: one bold sentence saying what happened in plain English, then <=5 bullets of detail (who, what moved, what it cost, what the contract did), then one line on whether anything looks unusual. No jargon without a plain-English gloss. Never invent data.\n\n${facts}`,
      { maxOutputTokens: 700 }
    );
    story = o.text; model = o.model;
  } catch { /* mechanical facts still ship */ }

  const content = `# Transaction Explained

\`${hash}\` · [view on Arcscan](${C.EXPLORER}/tx/${hash})

${story}

## The facts
- Status: **${tx.status === "ok" ? "✅ succeeded" : `❌ ${tx.status}`}**${tx.revert_reason ? ` — ${tx.revert_reason}` : ""}
- Action: \`${method}\`
- From: [${C.short(tx.from?.hash)}](${C.EXPLORER}/address/${tx.from?.hash})
- To: [${C.short(tx.to?.hash)}](${C.EXPLORER}/address/${tx.to?.hash})${tx.to?.name ? ` — ${tx.to.name}` : ""}${tx.to?.is_contract ? " *(contract)*" : ""}
- Native USDC sent: ${C.nat(tx.value)}
- Fee paid: ${C.nat(tx.fee?.value)} USDC
- Block ${tx.block_number} · ${C.ago(tx.timestamp)}

## What moved
${moves.length ? moves.join("\n") : "- no token transfers in this transaction"}

## Events emitted
${Object.keys(eventCounts).length ? Object.entries(eventCounts).map(([e, n]) => `- \`${e}\` ×${n}`).join("\n") : "- none"}

---
*Generated by the Transaction Explainer agent (Arc chain data + model: ${model}).*
`;
  return { content, contentType: "text/markdown" };
}

module.exports = { key: "tx-explain", title: "Transaction Explainer", run };
