"use strict";

/**
 * Arc-native agent — Wallet Report.
 * Input:  { address }
 * Output: what this wallet is, what it holds, how it behaves, who it deals with.
 * Free chain data; the LLM only writes the read-out at the end.
 */

const { generate } = require("../llm");
const C = require("./_chain");

async function run(input) {
  const address = String(input.address || "").trim();
  if (!C.isAddress(address)) throw new Error("input must be a 0x… address (40 hex chars)");

  // No filter param: this Blockscout returns an empty set for filter=to|from,
  // and its /counters endpoint reports zeros — so the sampled feed is the truth.
  const [info, tokens, txs] = await Promise.all([
    C.get(`/addresses/${address}`),
    C.get(`/addresses/${address}/token-balances`),
    C.get(`/addresses/${address}/transactions`),
  ]);
  if (!info) throw new Error(`address not found on ${C.CHAIN_LABEL}`);

  const items = txs?.items || [];
  const out = items.filter((t) => t.from?.hash?.toLowerCase() === address.toLowerCase());
  const inn = items.filter((t) => t.to?.hash?.toLowerCase() === address.toLowerCase());

  const counterparties = {};
  for (const t of items) {
    const other = t.from?.hash?.toLowerCase() === address.toLowerCase() ? t.to?.hash : t.from?.hash;
    if (other) counterparties[other] = (counterparties[other] || 0) + 1;
  }
  const topPartners = Object.entries(counterparties).sort((a, b) => b[1] - a[1]).slice(0, 5);

  const holdings = (tokens || [])
    .filter((t) => t.token?.symbol)
    .slice(0, 10)
    .map((t) => `- ${C.amt(t.value, t.token.decimals)} ${t.token.symbol}${t.token.name ? ` (${t.token.name})` : ""}`);

  const methods = {};
  for (const t of out) { const m = t.method || t.decoded_input?.method_call?.split("(")[0] || "transfer"; methods[m] = (methods[m] || 0) + 1; }
  const topMethods = Object.entries(methods).sort((a, b) => b[1] - a[1]).slice(0, 6);

  const facts = `type: ${info.is_contract ? "contract" : "wallet (EOA)"}
native_usdc_balance: ${C.nat(info.coin_balance)}
transactions_in_sample: ${items.length}
recent_sent: ${out.length}
recent_received: ${inn.length}
last_activity: ${items[0]?.timestamp ? C.ago(items[0].timestamp) : "unknown"}
top_actions: ${topMethods.map(([m, n]) => `${m} x${n}`).join(", ") || "none"}
token_holdings: ${holdings.length}
top_counterparties: ${topPartners.map(([a, n]) => `${C.short(a)} x${n}`).join(", ") || "none"}`;

  let read = "(behaviour read unavailable)", model = "-";
  try {
    const o = await generate(
      `You are a blockchain analyst. From ONLY these observed facts about an address on Arc (a stablecoin chain where USDC is the gas token), write <=140 words of markdown bullets: what this address appears to be used for, how active it is, and anything notable or unusual. Never invent data.\n\n${facts}`,
      { maxOutputTokens: 512 }
    );
    read = o.text; model = o.model;
  } catch { /* mechanical report still ships */ }

  const content = `# Wallet Report: ${C.short(address)}

\`${address}\` · [view on Arcscan](${C.EXPLORER}/address/${address})

## Position
- Type: **${info.is_contract ? "Contract" : "Wallet (EOA)"}**
- Native USDC balance: **${C.nat(info.coin_balance)} USDC**
- Transactions in this sample: **${items.length}**${items.length >= 50 ? " (most recent page)" : ""}
- Last activity: **${items[0]?.timestamp ? C.ago(items[0].timestamp) : "unknown"}**

## Token holdings
${holdings.length ? holdings.join("\n") : "- none found"}

## Recent behaviour (last ${items.length} transactions)
- Sent: ${out.length} · Received: ${inn.length}
- Most-used actions: ${topMethods.length ? topMethods.map(([m, n]) => `\`${m}\` ×${n}`).join(", ") : "—"}

## Frequent counterparties
${topPartners.length ? topPartners.map(([a, n]) => `- [${C.short(a)}](${C.EXPLORER}/address/${a}) — ${n} interactions`).join("\n") : "- none found"}

## Analyst read
${read}

---
*Generated by the Wallet Report agent (Arc chain data + model: ${model}).*
`;
  return { content, contentType: "text/markdown" };
}

module.exports = { key: "wallet-report", title: "Wallet Report", run };
